In [1]:
import numpy as np

### Dot Product

In [4]:
x,y= np.array([[-2],[2]]),np.array([[4],[-3]])
np.dot(x.T,y)

array([[-14]])

In [5]:
x,y= np.array([[-2],[2]]),np.array([[4],[-3]])
x.T @ y

array([[-14]])

### Gaussian Elimination

In [1]:
import numpy as np

##### Function swap rows

In [2]:
def swaprows(M,row_index_1,row_index_2):
    M= M.copy()
    M[[row_index_1,row_index_2]] = M[[row_index_2,row_index_1]]
    return M

In [10]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)


[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [11]:
M_swapped = swaprows(M,0,2)
print(M_swapped)

[[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]


##### Finding the first non-zero value in a column starting from a specific value

In [17]:
def get_index_first_non_zero_value_from_column(M,column,starting_row):
    column_array = M[starting_row:,column]
    for i , val in enumerate(column_array):
     # To check for non-zero values, you must always use np.isclose instead of doing "val == 0".
        if not np.isclose(val,0,atol =1e-5):
            row_index = i + starting_row
            return row_index
    return -1

In [18]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [19]:
#If you search for a value below the first column starting at the first row,
#  the function should return -1:
print(get_index_first_non_zero_value_from_column(N, column = 0, starting_row = 0))

-1


In [20]:
#Searching for the first non zero value in the last column starting from row with index 2, 
#it should return 3 (index corresponding to the value 7).
print(get_index_first_non_zero_value_from_column(N, column = 4, starting_row = 2))

3


##### Find the first non zero element for any row

In [21]:
def get_index_first_non_zero_value_from_row(M,row,augmented=False):
    """
    Find the index of the first non-zero value in the specified row of the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to search for non-zero values.
    - row (int): The index of the row to search.
    - augmented (bool): Pass this True if you are dealing with an augmented matrix, 
                        so it will ignore the constant values (the last column in the augmented matrix).

    Returns:
    int: The index of the first non-zero value in the specified row.
                Returns -1 if no non-zero value is found.
    """
    M = M.copy()
       # If it is an augmented matrix, then ignore the constant values
    if augmented == True:
        # Isolating the coefficient matrix (removing the constant terms)
        M = M[:,:-1]

    row_array = M[row]
    for i ,val in enumerate(row_array):
        if not np.isclose(val,0,atol=1e-5):
            return i
    return -1

##### An augmented matrix is a matrix that includes both the coefficients and the constants from a system of linear equations. It's used to apply row operations and solve the system using methods such as Gaussian elimination or Gauss-Jordan elimination. The augmented matrix for a system of equations is created by appending the constants (right-hand side values) as an additional column to the coefficient matrix.

In [22]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


###### 
Now, let's pass the argument augmented = True. This will make the algorithm consider  𝑁
𝑁
  an augmented matrix, therefore the last column will be removed from consideration. Now, the output for row 3 (starting from 0) should be different, excluding the last column, the output should be -1 as well, since in the coefficient matrix (the matrix without the last column) there is no non-zero element:

In [24]:
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')
# because it just ignored the last column in gaussian elimination

Output for row 3: -1


#### Constructing the augmented matrix

In [25]:
def augmented_matrix(A, B):
    """
    Create an augmented matrix by horizontally stacking two matrices A and B.

    Parameters:
    - A (numpy.array): First matrix.
    - B (numpy.array): Second matrix.

    Returns:
    - numpy.array: Augmented matrix obtained by horizontally stacking A and B.
    """
    augmented_M = np.hstack((A,B))
    return augmented_M

In [26]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


In [1]:
import numpy as np

def augmented_matrix(A, B):
    augmented_M = np.hstack((A, B))
    return augmented_M

def get_index_first_non_zero_value_from_column(M, start_row, col):
    for i in range(start_row, M.shape[0]): #M.shape[0] gives the no of rows in the array or matrix
        if not np.isclose(M[i, col], 0):
            return i
    raise ValueError("No non-zero element found in the column.")

def swap_rows(M, row1, row2):
    M[[row1, row2]] = M[[row2, row1]]
    return M

def row_echelon_form(A, B):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        return 'Singular system'
    A = A.copy()
    B = B.copy()
    A = A.astype('float64')
    B = B.astype('float64')
    num_rows = len(A)
    M = augmented_matrix(A, B)
    for row in range(num_rows):
        pivot_candidate = M[row, row]
        if np.isclose(pivot_candidate, 0):
            first_non_zero_value_below_pivot_candidate = get_index_first_non_zero_value_from_column(M, row, row)
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate)
            pivot = M[row, row]
        else:
            pivot = pivot_candidate
        M[row] = (1/pivot) * M[row]
        for j in range(row + 1, num_rows):
            value_below_pivot = M[j, row]
            M[j] = M[j] - value_below_pivot * M[row]
    return M


In [28]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

array([[1. , 2. , 3. , 1. ],
       [0. , 1. , 0. , 2. ],
       [0. , 0. , 1. , 0.8]])