#### used for nominal categorical data

In [77]:
import numpy as np
import pandas as pd

In [78]:
df = pd.read_csv(r"C:\Users\hp\OneDrive\codes\python\Learn_ML\1. Datasets\cars.csv").drop(columns=["km_driven","owner"])

In [79]:
df.head()

brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [80]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [81]:
X_train ,X_test ,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,random_state=42)

In [82]:
X_train

brand    fuel
6518      Tata  Petrol
6144     Honda  Petrol
6381   Hyundai  Diesel
438     Maruti  Diesel
5939    Maruti  Petrol
...        ...     ...
5226  Mahindra  Diesel
5390    Maruti  Diesel
860    Hyundai  Petrol
7603    Maruti  Diesel
7270    Maruti  Petrol

[6502 rows x 2 columns]

In [83]:
oe = OneHotEncoder(drop='first',sparse_output=False)

In [84]:
X_train = oe.fit_transform(X_train)

In [85]:
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [86]:
X_train.shape

(6502, 34)

In [87]:
oe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [88]:
oe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [89]:
oe.get_feature_names_out()

array(['brand_Ashok', 'brand_Audi', 'brand_BMW', 'brand_Chevrolet',
       'brand_Daewoo', 'brand_Datsun', 'brand_Fiat', 'brand_Force',
       'brand_Ford', 'brand_Honda', 'brand_Hyundai', 'brand_Isuzu',
       'brand_Jaguar', 'brand_Jeep', 'brand_Kia', 'brand_Land',
       'brand_Lexus', 'brand_MG', 'brand_Mahindra', 'brand_Maruti',
       'brand_Mercedes-Benz', 'brand_Mitsubishi', 'brand_Nissan',
       'brand_Opel', 'brand_Peugeot', 'brand_Renault', 'brand_Skoda',
       'brand_Tata', 'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo',
       'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [90]:
pd.DataFrame(X_train,columns=oe.get_feature_names_out())

brand_Ashok  brand_Audi  brand_BMW  brand_Chevrolet  brand_Daewoo  \
0             0.0         0.0        0.0              0.0           0.0   
1             0.0         0.0        0.0              0.0           0.0   
2             0.0         0.0        0.0              0.0           0.0   
3             0.0         0.0        0.0              0.0           0.0   
4             0.0         0.0        0.0              0.0           0.0   
...           ...         ...        ...              ...           ...   
6497          0.0         0.0        0.0              0.0           0.0   
6498          0.0         0.0        0.0              0.0           0.0   
6499          0.0         0.0        0.0              0.0           0.0   
6500          0.0         0.0        0.0              0.0           0.0   
6501          0.0         0.0        0.0              0.0           0.0   

      brand_Datsun  brand_Fiat  brand_Force  brand_Ford  brand_Honda  ...  \
0              0.0         0.0          0.0         0.0          0.0  ...   
1              0.0         0.0          0.0         0.0          1.0  ...   
2              0.0         0.0          0.0         0.0          0.0  ...   
3              0.0         0.0          0.0         0.0          0.0  ...   
4              0.0         0.0          0.0         0.0          0.0  ...   
...            ...         ...          ...         ...          ...  ...   
6497           0.0         0.0          0.0         0.0          0.0  ...   
6498           0.0         0.0          0.0         0.0          0.0  ...   
6499           0.0         0.0          0.0         0.0          0.0  ...   
6500           0.0         0.0          0.0         0.0          0.0  ...   
6501           0.0         0.0          0.0         0.0          0.0  ...   

      brand_Peugeot  brand_Renault  brand_Skoda  brand_Tata  brand_Toyota  \
0               0.0            0.0          0.0         1.0           0.0   
1               0.0            0.0          0.0         0.0           0.0   
2               0.0            0.0          0.0         0.0           0.0   
3               0.0            0.0          0.0         0.0           0.0   
4               0.0            0.0          0.0         0.0           0.0   
...             ...            ...          ...         ...           ...   
6497            0.0            0.0          0.0         0.0           0.0   
6498            0.0            0.0          0.0         0.0           0.0   
6499            0.0            0.0          0.0         0.0           0.0   
6500            0.0            0.0          0.0         0.0           0.0   
6501            0.0            0.0          0.0         0.0           0.0   

      brand_Volkswagen  brand_Volvo  fuel_Diesel  fuel_LPG  fuel_Petrol  
0                  0.0          0.0          0.0       0.0          1.0  
1                  0.0          0.0          0.0       0.0          1.0  
2                  0.0          0.0          1.0       0.0          0.0  
3                  0.0          0.0          1.0       0.0          0.0  
4                  0.0          0.0          0.0       0.0          1.0  
...                ...          ...          ...       ...          ...  
6497               0.0          0.0          1.0       0.0          0.0  
6498               0.0          0.0          1.0       0.0          0.0  
6499               0.0          0.0          0.0       0.0          1.0  
6500               0.0          0.0          1.0       0.0          0.0  
6501               0.0          0.0          0.0       0.0          1.0  

[6502 rows x 34 columns]

oe.inverse_transform(pass an np.array it will work) 

## Rare categories

### min_frequency method

In [93]:
df = pd.read_csv(r"C:\Users\hp\OneDrive\codes\python\Learn_ML\1. Datasets\cars.csv").drop(columns=["km_driven","owner"])
df.head()

brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [94]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,random_state=42)

In [95]:
ohe = OneHotEncoder(sparse_output=False,handle_unknown="ignore",min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [96]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

### max_categories

In [98]:
ohe = OneHotEncoder(sparse_output=False,handle_unknown="ignore",max_categories=5)
ohe.fit_transform(X_train).shape

(6502, 9)

In [100]:
ohe.get_feature_names_out()

array(['brand_Hyundai', 'brand_Mahindra', 'brand_Maruti', 'brand_Tata',
       'brand_infrequent_sklearn', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

#### handle_unknown can be used to handle values which you are unaware of 

## When we need to One Hot encoding on traget columns LabelBinarizer

## LabelBinarizer

#### The LabelBinarizer in scikit-learn is a Class used to transform multi-class labels to binary labels (1 vs all). Essentially, it's used for one-hot encoding of labels. This is particularly useful in classification tasks where you need to convert categorical target variables into a format that's suitable for machine learning models, especially those that require a binary or one-hot encoded format for the target variable.

In [105]:
from sklearn.preprocessing import LabelBinarizer
# Sample target variable for a multi-class classification problem
y = ['cat', 'dog','cat','fish','dog','cat']
# Initialize the LabelBånarizer
lb = LabelBinarizer()
y_binarized = lb.fit_transform(y)
# Fit and transform the target variable
print( "Binarized labels: \n", y_binarized)
# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)
print( "Original labels: \n", y_original)

Binarized labels: 
 [[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels: 
 ['cat' 'dog' 'cat' 'fish' 'dog' 'cat']
