In [2]:
import numpy as np

#### Data Centering 

In [4]:
data = np.array([10,20,30,40,50])

In [5]:
mean = data.mean()

In [6]:
mean

np.float64(30.0)

In [7]:
centered_data = data - mean

In [8]:
centered_data

array([-20., -10.,   0.,  10.,  20.])

#### Data Standardization

In [10]:
std_dev = np.std(data)

In [11]:
standardized_data = (data - mean)/std_dev

In [12]:
standardized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

#### Log Transformation

In [14]:
log_transformed_data = np.log(data)

In [15]:
log_transformed_data

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [16]:
print("Centred Data",centered_data)
print("Standardized Data",standardized_data)
print("Log Transformed Data",log_transformed_data)

Centred Data [-20. -10.   0.  10.  20.]
Standardized Data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Log Transformed Data [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
